version: '3.7'

services:

  brightwheel-django-local:
    restart: always
    image: brightwheel-django-local
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    entrypoint: /code/docker/local/django/start.sh