#!/bin/sh

# use the django manage.py command from within a docker container from shell on host

ARGS="$@"

if [[ -z $ARGS ]]
then
    ARGS="help"
fi

docker-compose exec brightwheel-django-local sh -c "cd /code/ && pipenv run python manage.py $ARGS"