"""
Django settings for brightwheel project.

Generated by 'django-admin startproject' using Django 3.0.3.
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'brightwheelemail',
    'django.contrib.staticfiles',

    'drf_yasg'
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': None
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
}

EMAIL_URL = os.environ.get('EMAIL_PROVIDER_URL')
EMAIL_PROVIDER = os.environ.get('EMAIL_PROVIDER')
API_KEY = os.environ.get('API_KEY')

ROOT_URLCONF = 'brightwheel.urls'

WSGI_APPLICATION = 'brightwheel.wsgi.application'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
